name: test
description: A test app for Simple Tuple!
version: 1.0.0
publish_to: none
homepage: https://github.com/iamtheblackunicorn/simpletuple
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  simpletuple:
    git: git://github.com/iamtheblackunicorn/simpletuple.git
