name: simpletuple
description: A tiny library to handle n-dimensional tuples.
version: 1.0.0-nullsafety.0
homepage: https://github.com/iamtheblackunicorn/simpletuple
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
